// Base de alimentos comunes (foco argentino).
// k = kcal por 100 g · p = gramos de la porción típica · u = descripción de la porción
// a = alias / otras formas de escribirlo. Los valores son estimaciones promedio.
const BASE_ALIMENTOS = [
  // ── Carnes y platos principales ──
  { n: "Milanesa de carne", a: ["milanesa", "milanga"], k: 250, p: 150, u: "1 milanesa mediana" },
  { n: "Milanesa de pollo", a: ["milanesa de pollo", "suprema"], k: 220, p: 150, u: "1 milanesa mediana" },
  { n: "Milanesa napolitana", a: ["napolitana"], k: 280, p: 200, u: "1 milanesa con jamón y queso" },
  { n: "Asado (vacío/costilla)", a: ["asado", "costilla", "vacio"], k: 290, p: 200, u: "1 porción" },
  { n: "Bife de carne", a: ["bife", "churrasco", "carne a la plancha"], k: 220, p: 150, u: "1 bife mediano" },
  { n: "Pollo al horno", a: ["pollo", "pata muslo"], k: 190, p: 180, u: "1 presa" },
  { n: "Pechuga de pollo a la plancha", a: ["pechuga"], k: 150, p: 150, u: "1 pechuga" },
  { n: "Chorizo", a: ["choripan sin pan", "chori"], k: 320, p: 80, u: "1 chorizo" },
  { n: "Choripán", a: ["choripan"], k: 300, p: 200, u: "1 choripán" },
  { n: "Hamburguesa casera (con pan)", a: ["hamburguesa"], k: 250, p: 250, u: "1 hamburguesa completa" },
  { n: "Hamburguesa de comida rápida", a: ["big mac", "whopper", "hamburguesa mcdonalds", "hamburguesa burger king"], k: 250, p: 220, u: "1 hamburguesa" },
  { n: "Panchos (salchicha con pan)", a: ["pancho", "salchicha con pan"], k: 280, p: 150, u: "1 pancho" },
  { n: "Salchicha", a: ["salchichas"], k: 290, p: 45, u: "1 salchicha" },
  { n: "Matambre a la pizza", a: ["matambre"], k: 260, p: 180, u: "1 porción" },
  { n: "Bondiola de cerdo", a: ["bondiola", "cerdo"], k: 260, p: 180, u: "1 porción" },
  { n: "Pescado a la plancha (merluza)", a: ["pescado", "merluza", "filet de merluza"], k: 110, p: 170, u: "1 filet" },
  { n: "Milanesa de pescado", a: ["milanesa de merluza"], k: 200, p: 150, u: "1 milanesa" },
  { n: "Atún al natural", a: ["atun", "lata de atun"], k: 110, p: 120, u: "1 lata escurrida" },
  { n: "Estofado / guiso de carne", a: ["guiso", "estofado", "guiso de lentejas con carne"], k: 130, p: 350, u: "1 plato" },
  { n: "Pastel de papa", a: ["pastel de papas"], k: 150, p: 350, u: "1 porción" },
  { n: "Albóndigas con salsa", a: ["albondigas"], k: 180, p: 250, u: "1 plato (4 albóndigas)" },

  // ── Pastas, arroz y pizza ──
  { n: "Fideos con salsa de tomate", a: ["fideos", "pasta", "fideos con tuco", "tallarines"], k: 150, p: 350, u: "1 plato" },
  { n: "Fideos con crema", a: ["pasta con crema"], k: 210, p: 350, u: "1 plato" },
  { n: "Ñoquis con salsa", a: ["noquis", "ñoquis"], k: 160, p: 300, u: "1 plato" },
  { n: "Ravioles con salsa", a: ["ravioles"], k: 180, p: 300, u: "1 plato" },
  { n: "Sorrentinos con salsa", a: ["sorrentinos"], k: 200, p: 300, u: "1 plato" },
  { n: "Canelones", a: ["canelones de verdura"], k: 160, p: 300, u: "2 canelones" },
  { n: "Lasaña", a: ["lasagna", "lasania"], k: 180, p: 300, u: "1 porción" },
  { n: "Arroz blanco cocido", a: ["arroz"], k: 130, p: 200, u: "1 plato" },
  { n: "Arroz con pollo", a: [], k: 160, p: 350, u: "1 plato" },
  { n: "Risotto", a: [], k: 170, p: 300, u: "1 plato" },
  { n: "Pizza de muzzarella", a: ["pizza", "muzza", "porcion de pizza"], k: 270, p: 120, u: "1 porción" },
  { n: "Pizza especial (jamón y morrón)", a: ["pizza especial", "pizza de jamon"], k: 250, p: 130, u: "1 porción" },
  { n: "Fugazzeta", a: ["fugazza"], k: 290, p: 130, u: "1 porción" },
  { n: "Fainá", a: ["faina"], k: 300, p: 80, u: "1 porción" },
  { n: "Polenta con salsa", a: ["polenta"], k: 110, p: 300, u: "1 plato" },

  // ── Empanadas, tartas y sándwiches ──
  { n: "Empanada de carne", a: ["empanada", "empanadas"], k: 280, p: 120, u: "1 empanada" },
  { n: "Empanada de pollo", a: ["empanadas de pollo"], k: 260, p: 120, u: "1 empanada" },
  { n: "Empanada de jamón y queso", a: ["empanada de queso", "empanadas de jamon y queso"], k: 300, p: 120, u: "1 empanada" },
  { n: "Empanada de humita", a: ["empanadas de humita"], k: 250, p: 120, u: "1 empanada" },
  { n: "Tarta de verdura", a: ["tarta", "tarta de acelga", "tarta de espinaca"], k: 180, p: 200, u: "1 porción" },
  { n: "Tarta de jamón y queso", a: ["tarta de queso"], k: 240, p: 200, u: "1 porción" },
  { n: "Sándwich de miga (jamón y queso)", a: ["sandwich de miga", "sanguche de miga", "miguitas"], k: 260, p: 55, u: "1 sándwich triple" },
  { n: "Tostado de jamón y queso", a: ["tostado", "carlitos", "sandwich tostado"], k: 250, p: 180, u: "1 tostado" },
  { n: "Sándwich de milanesa", a: ["sanguche de milanesa", "sandwich de milanesa"], k: 240, p: 350, u: "1 sándwich completo" },
  { n: "Lomito completo", a: ["lomito"], k: 220, p: 400, u: "1 lomito" },
  { n: "Pebete de jamón y queso", a: ["pebete"], k: 260, p: 150, u: "1 pebete" },

  // ── Guarniciones y verduras ──
  { n: "Papas fritas", a: ["fritas", "papafritas"], k: 310, p: 150, u: "1 porción" },
  { n: "Puré de papa", a: ["pure", "pure de papas"], k: 100, p: 200, u: "1 porción" },
  { n: "Papa al horno", a: ["papas al horno"], k: 110, p: 200, u: "1 porción" },
  { n: "Batata / boniato asado", a: ["batata", "boniato", "boniatos", "batatas", "boniatos asados", "batatas asadas", "boniato asado", "batata asada"], k: 100, p: 200, u: "1 porción" },
  { n: "Puré de calabaza", a: ["pure de zapallo", "pure de calabaza"], k: 60, p: 200, u: "1 porción" },
  { n: "Ensalada mixta (lechuga y tomate)", a: ["ensalada", "ensalada mixta"], k: 20, p: 150, u: "1 plato (sin aceite)" },
  { n: "Ensalada rusa", a: [], k: 140, p: 200, u: "1 porción" },
  { n: "Ensalada César", a: ["ensalada cesar"], k: 150, p: 250, u: "1 plato" },
  { n: "Tomate", a: ["tomates"], k: 18, p: 120, u: "1 tomate" },
  { n: "Lechuga", a: [], k: 15, p: 50, u: "1 taza" },
  { n: "Zanahoria", a: [], k: 40, p: 80, u: "1 zanahoria" },
  { n: "Zapallo / calabaza", a: ["zapallo", "calabaza"], k: 30, p: 150, u: "1 porción" },
  { n: "Brócoli cocido", a: ["brocoli"], k: 35, p: 150, u: "1 porción" },
  { n: "Verduras salteadas", a: ["salteado de verduras", "wok de verduras"], k: 70, p: 200, u: "1 porción" },
  { n: "Choclo", a: ["maiz"], k: 95, p: 150, u: "1 choclo" },
  { n: "Lentejas cocidas", a: ["lentejas"], k: 115, p: 200, u: "1 porción" },
  { n: "Garbanzos cocidos", a: ["garbanzos"], k: 160, p: 200, u: "1 porción" },
  { n: "Aceite (una cucharada)", a: ["aceite", "aceite de oliva"], k: 880, p: 15, u: "1 cucharada" },
  { n: "Palta", a: ["aguacate", "media palta"], k: 160, p: 70, u: "media palta" },

  // ── Huevos y lácteos ──
  { n: "Huevo frito", a: ["huevos fritos"], k: 200, p: 55, u: "1 huevo" },
  { n: "Huevo duro", a: ["huevos duros", "huevo hervido"], k: 155, p: 55, u: "1 huevo" },
  { n: "Huevo revuelto", a: ["huevos revueltos", "revuelto"], k: 170, p: 60, u: "1 huevo" },
  { n: "Tortilla de papa", a: ["tortilla"], k: 190, p: 200, u: "1 porción" },
  { n: "Queso port salut", a: ["queso", "queso cremoso"], k: 300, p: 30, u: "1 feta gruesa" },
  { n: "Queso rallado", a: [], k: 400, p: 10, u: "1 cucharada" },
  { n: "Yogur entero", a: ["yogur", "yogurt"], k: 80, p: 190, u: "1 pote" },
  { n: "Yogur Tregar con frutas (entero, arándano)", a: ["yogur tregar", "yogur de arandanos", "yogur arandano", "yogur con frutas", "tregar arandano"], k: 106, p: 150, u: "1 pote (150 g · 159 kcal)" },
  { n: "Yogur Tregar Tops con copos y miel (descremado)", a: ["yogur tops", "tops", "tregar tops", "yogur con copos", "yogur con cereales", "yogur descremado con copos"], k: 76, p: 164, u: "1 vaso (164 g · 125 kcal)" },
  { n: "Yogur descremado", a: ["yogur light", "ser"], k: 45, p: 190, u: "1 pote" },
  { n: "Leche entera", a: ["leche", "vaso de leche"], k: 60, p: 200, u: "1 vaso" },
  { n: "Leche descremada", a: [], k: 35, p: 200, u: "1 vaso" },
  { n: "Queso crema", a: ["casancrem", "finlandia"], k: 240, p: 20, u: "1 cucharada" },
  { n: "Dulce de leche", a: [], k: 310, p: 20, u: "1 cucharada" },
  { n: "Manteca", a: [], k: 720, p: 10, u: "1 rulito" },
  { n: "Jamón cocido", a: ["jamon", "fiambre"], k: 110, p: 30, u: "2 fetas" },
  { n: "Salame", a: ["salamin"], k: 380, p: 30, u: "5 rodajas" },

  // ── Panificados y desayuno ──
  { n: "Pan francés / mignon", a: ["pan", "mignon", "flautita"], k: 270, p: 50, u: "1 mignon" },
  { n: "Pan lactal", a: ["pan de molde", "rebanada de pan"], k: 260, p: 26, u: "1 rebanada" },
  { n: "Tostada con manteca y mermelada", a: ["tostada", "tostadas"], k: 300, p: 40, u: "1 tostada armada" },
  { n: "Medialuna", a: ["medialunas", "media luna"], k: 390, p: 45, u: "1 medialuna" },
  { n: "Factura (promedio)", a: ["factura", "facturas", "bola de fraile", "vigilante"], k: 380, p: 55, u: "1 factura" },
  { n: "Criollito / bizcocho de grasa", a: ["criollos", "bizcochos", "bizcochitos"], k: 450, p: 15, u: "1 bizcochito" },
  { n: "Galletitas de agua", a: ["crackers", "galletas de agua"], k: 420, p: 24, u: "4 galletitas" },
  { n: "Galletitas dulces", a: ["galletitas", "galletas"], k: 470, p: 30, u: "3 galletitas" },
  { n: "Avena", a: ["avena arrollada"], k: 370, p: 40, u: "4 cucharadas" },
  { n: "Cereales de desayuno", a: ["cereales", "copos"], k: 380, p: 40, u: "1 taza" },
  { n: "Mermelada", a: [], k: 250, p: 20, u: "1 cucharada" },
  { n: "Miel", a: [], k: 300, p: 20, u: "1 cucharada" },
  { n: "Vainillas", a: ["vainilla"], k: 390, p: 12, u: "1 vainilla" },
  { n: "Budín (porción)", a: ["budin"], k: 400, p: 60, u: "1 rodaja" },

  // ── Frutas ──
  { n: "Banana", a: ["bananas"], k: 90, p: 120, u: "1 banana" },
  { n: "Manzana", a: ["manzanas"], k: 52, p: 150, u: "1 manzana" },
  { n: "Naranja", a: ["naranjas"], k: 47, p: 150, u: "1 naranja" },
  { n: "Mandarina", a: ["mandarinas"], k: 53, p: 100, u: "1 mandarina" },
  { n: "Pera", a: ["peras"], k: 57, p: 160, u: "1 pera" },
  { n: "Uvas", a: ["uva"], k: 69, p: 100, u: "1 racimo chico" },
  { n: "Frutillas", a: ["frutilla", "fresas"], k: 33, p: 150, u: "1 taza" },
  { n: "Durazno", a: ["duraznos"], k: 39, p: 150, u: "1 durazno" },
  { n: "Sandía", a: ["sandia"], k: 30, p: 200, u: "1 tajada" },
  { n: "Melón", a: ["melon"], k: 34, p: 200, u: "1 tajada" },
  { n: "Kiwi", a: [], k: 60, p: 75, u: "1 kiwi" },
  { n: "Ensalada de frutas", a: [], k: 60, p: 250, u: "1 compotera" },

  // ── Bebidas ──
  { n: "Gaseosa (cola)", a: ["coca", "coca cola", "gaseosa", "pepsi"], k: 42, p: 350, u: "1 vaso grande / lata" },
  { n: "Gaseosa light/zero", a: ["coca zero", "coca light", "gaseosa zero"], k: 0, p: 350, u: "1 vaso grande / lata" },
  { n: "Jugo de naranja exprimido", a: ["jugo de naranja", "jugo exprimido"], k: 45, p: 250, u: "1 vaso" },
  { n: "Jugo en polvo preparado", a: ["jugo", "tang"], k: 35, p: 250, u: "1 vaso" },
  { n: "Cerveza", a: ["birra"], k: 43, p: 330, u: "1 lata / porrón" },
  { n: "Vino tinto", a: ["vino", "copa de vino"], k: 85, p: 150, u: "1 copa" },
  { n: "Fernet con coca", a: ["fernet"], k: 75, p: 250, u: "1 vaso" },
  { n: "Café solo", a: ["cafe", "cafe negro", "espresso"], k: 2, p: 100, u: "1 pocillo" },
  { n: "Café con leche", a: ["cafe con leche", "lagrima"], k: 45, p: 200, u: "1 taza (con azúcar aparte)" },
  { n: "Cortado", a: [], k: 25, p: 100, u: "1 pocillo" },
  { n: "Mate cocido", a: [], k: 3, p: 200, u: "1 taza (sin azúcar)" },
  { n: "Mate (cebado)", a: ["mate", "mates"], k: 10, p: 500, u: "1 ronda (sin azúcar)" },
  { n: "Té", a: ["te", "te con limon"], k: 2, p: 200, u: "1 taza (sin azúcar)" },
  { n: "Azúcar (cucharadita)", a: ["azucar"], k: 400, p: 6, u: "1 cucharadita" },
  { n: "Licuado de banana con leche", a: ["licuado", "licuado de banana"], k: 90, p: 300, u: "1 vaso grande" },
  { n: "Agua", a: ["agua mineral", "soda"], k: 0, p: 250, u: "1 vaso" },

  // ── Snacks y dulces ──
  { n: "Alfajor", a: ["alfajores", "alfajor triple"], k: 450, p: 55, u: "1 alfajor" },
  { n: "Chocolate", a: ["chocolate con leche", "barra de chocolate"], k: 540, p: 25, u: "1/4 de barra" },
  { n: "Helado", a: ["helado de crema", "cucurucho"], k: 210, p: 120, u: "1 cucurucho / vasito" },
  { n: "Papas fritas de bolsa", a: ["papitas", "lays", "chizitos"], k: 530, p: 40, u: "1 bolsita chica" },
  { n: "Maní", a: ["mani", "mani tostado"], k: 590, p: 30, u: "1 puñado" },
  { n: "Mix de frutos secos", a: ["frutos secos", "nueces", "almendras"], k: 600, p: 30, u: "1 puñado" },
  { n: "Turrón de maní", a: ["turron"], k: 470, p: 25, u: "1 turrón" },
  { n: "Barrita de cereal", a: ["barrita", "cereal bar"], k: 400, p: 23, u: "1 barrita" },
  { n: "Torta (porción)", a: ["torta", "torta de cumpleanos", "chocotorta"], k: 380, p: 100, u: "1 porción" },
  { n: "Flan con dulce de leche", a: ["flan"], k: 180, p: 150, u: "1 porción" },
  { n: "Gelatina", a: [], k: 60, p: 150, u: "1 porción" },
  { n: "Pochoclo", a: ["popcorn", "palomitas"], k: 400, p: 50, u: "1 bolsa chica" },
  { n: "Aceitunas", a: ["aceituna"], k: 130, p: 30, u: "8 aceitunas" },
  { n: "Picada (quesos y fiambres)", a: ["picada"], k: 350, p: 150, u: "1 plato individual" },
];
