// Menú del trabajo (Food Service / catering.foodservice.com.ar).
// Las calorías son FIJAS POR CATEGORÍA (verificado en la web: el rango no cambia entre días).
// Lo único que rota semana a semana son los platos: actualizar PLATOS_TRABAJO con el PDF nuevo.
// Semanas cargadas: hasta 2026-10-12 (actualizar pasando los PDF nuevos a Claude).

const CATEGORIAS_TRABAJO = {
  "Plato Principal":      { kcal: 850, alias: ["plato principal", "principal", "menu del dia"] },
  "Plato Principal 2":    { kcal: 850, alias: ["plato principal 2", "principal 2"] },
  "Hipernutritivo":       { kcal: 900, alias: ["hipernutritivo", "hiper"] },
  "Healthy Food":         { kcal: 500, alias: ["healthy", "healthy food", "dieta", "sin sal", "dieta sin sal"] },
  "Plato Light":          { kcal: 700, alias: ["light", "plato light"] },
  "Ensalada SAP":         { kcal: 400, alias: ["ensalada sap", "sap"] },
  "Tarta":                { kcal: 400, alias: ["tarta del trabajo"] },
  "Sandwich":             { kcal: 650, alias: ["sandwich del trabajo", "sanguche del trabajo"] },
  "Pizza":                { kcal: 550, alias: ["pizza del trabajo"] },
  "Pasta":                { kcal: 750, alias: ["pasta del trabajo"] },
  "Vegetariano":          { kcal: 700, alias: ["vegetariano", "veggie"] },
  "Plato Veggie":         { kcal: 500, alias: ["plato veggie"] },
  "Show":                 { kcal: 700, alias: ["show", "empanadas show"] },
  "Opcion Milanesa":      { kcal: 388, alias: ["opcion milanesa", "milanesa del dia", "milanesa del trabajo"] },
  "Tortilla y Omelette":  { kcal: 500, alias: ["tortilla del trabajo", "omelette"] },
  "VAMOS CAMPEONES":      { kcal: 500, alias: ["vamos campeones", "campeones"] },
  "Wok Gourmet":          { kcal: 500, alias: ["wok"] },
  "Wrap Gourmet":         { kcal: 500, alias: ["wrap"] },
  "Hamburguesa Especial": { kcal: 900, alias: ["hamburguesa especial", "burger especial"] },
  "Ensalada Gourmet":     { kcal: 500, alias: ["ensalada gourmet"] },
  "Plato Etnico":         { kcal: 600, alias: ["etnico", "plato etnico"] },
  "Plato Vegano Gourmet": { kcal: 500, alias: ["vegano", "plato vegano"] },
};

// d = fechas en que se sirve (para priorizar el plato de HOY en las búsquedas)
const PLATOS_TRABAJO = [
// 454 platos · del 2026-07-28 al 2026-10-12 · fusionado por Claude
  { n: "Falafel vegano con emulsión de remolachas y zanahorias con sésamo", cat: "Plato Vegano Gourmet", d: ["2026-07-28", "2026-09-01"] },
  { n: "Omelette de choclo, morrón y queso", cat: "Tortilla y Omelette", d: ["2026-07-28"] },
  { n: "Clasic pulled chicken burger con queso, tomate y cebollas caramelizadas, acompañada de papas provenzal", cat: "Hamburguesa Especial", d: ["2026-07-28"] },
  { n: "Fitbowl de garbanzos y lentejas con cebolla, pollo, tomates cherry, lechuga, queso y choclo", cat: "Ensalada Gourmet", d: ["2026-07-28", "2026-09-14"] },
  { n: "Milanesa de carne a la fugazzetta, acompañada de coditos con salsa de queso y verdeo", cat: "Opcion Milanesa", d: ["2026-07-28", "2026-08-11"] },
  { n: "Mc Allister de carne con queso cheddar, cebolla crispy, jamón agridulce y barbacoa ahumada, acompañada de papas rústicas", cat: "VAMOS CAMPEONES", d: ["2026-07-28", "2026-08-12", "2026-09-01", "2026-09-30"] },
  { n: "Jamón de cerdo a la pizza con batatas rústicas", cat: "Plato Principal", d: ["2026-07-28"] },
  { n: "Cazuela de mejillones con arroz", cat: "Hipernutritivo", d: ["2026-07-28"] },
  { n: "Pollo con puré emulsión de zanahorias", cat: "Healthy Food", d: ["2026-07-28"] },
  { n: "Hojas verdes, papa, jamón, queso, tomates cherry, pesto de albahaca, croutons y semillas SAP", cat: "Ensalada SAP", d: ["2026-07-28"] },
  { n: "Falafel con emulsión de remolachas y zanahorias con sésamo", cat: "Plato Veggie", d: ["2026-07-28", "2026-09-01"] },
  { n: "Wok de arroz y porotos negros, vegetales salteados, ternera en cocción lenta, choclo tostado y salsa huancaina", cat: "Wok Gourmet", d: ["2026-07-28", "2026-08-05", "2026-08-19", "2026-09-03"] },
  { n: "Wrap de cerdo, vegetales y mostaza con batatas glaseadas", cat: "Wrap Gourmet", d: ["2026-07-28", "2026-09-08"] },
  { n: "Font de vegetales asados, carne y cubos de queso con reducción de soja agridulce y semillas", cat: "Plato Light", d: ["2026-07-28"] },
  { n: "Arroz persa con pollo marinado y frutos secos", cat: "Plato Etnico", d: ["2026-07-28", "2026-09-09"] },
  { n: "Polenta con queso, vegetales asados y pesto de albahaca", cat: "Vegetariano", d: ["2026-07-28", "2026-09-03"] },
  { n: "Sandwiches de miga de jamón y queso", cat: "Sandwich", d: ["2026-07-28", "2026-08-04", "2026-08-11", "2026-08-18", "2026-09-01", "2026-09-08", "2026-09-29", "2026-10-06"] },
  { n: "Tarta de berenjenas, tomate seco y queso", cat: "Tarta", d: ["2026-07-28"] },
  { n: "Pizza de muzzarella con pesto de albahaca", cat: "Pizza", d: ["2026-07-28"] },
  { n: "Mostacholes al pesto", cat: "Pasta", d: ["2026-07-28"] },
  { n: "Empanadas de carne, pollo, jamón y queso, choclo", cat: "Show", d: ["2026-07-28", "2026-07-30", "2026-08-11", "2026-09-08", "2026-09-10", "2026-10-06", "2026-10-08"] },
  { n: "Ratatouille con quinoa", cat: "Plato Vegano Gourmet", d: ["2026-07-29", "2026-08-19", "2026-09-10", "2026-10-07"] },
  { n: "Tortilla de papas a la provenzal", cat: "Tortilla y Omelette", d: ["2026-07-29", "2026-08-19", "2026-09-02", "2026-10-05"] },
  { n: "Hamburguesa pons con cebolla frita, queso y barbacoa, acompañada de calabazas rústicas", cat: "Hamburguesa Especial", d: ["2026-07-29"] },
  { n: "Marroquí salad, mix de verdes, garbanzos, aceitunas negras, remolacha, tomate, pepino y queso", cat: "Ensalada Gourmet", d: ["2026-07-29", "2026-08-20", "2026-09-09", "2026-10-01"] },
  { n: "Milanesa de zucchinis napolitana con puré de papas al verdeo", cat: "Opcion Milanesa", d: ["2026-07-29"] },
  { n: "Mc tasty con lechuga, tomate y cebollas caramelizadas, acompañada de papas rusticas al pimentón", cat: "VAMOS CAMPEONES", d: ["2026-07-29", "2026-08-04", "2026-08-18", "2026-09-09", "2026-10-01", "2026-10-07"] },
  { n: "Pechuga rellena en reducción de soja ahumada y mix de semillas, acompañada de arroz salteado con vegetales", cat: "Plato Principal", d: ["2026-07-29"] },
  { n: "Locro con salsa picante", cat: "Hipernutritivo", d: ["2026-07-29", "2026-09-03"] },
  { n: "Carne asada en cocción lenta con panaché de choclo, papa y remolacha", cat: "Healthy Food", d: ["2026-07-29"] },
  { n: "Ensalada cesar con pollo, croutones y mix de semillas SAP", cat: "Ensalada SAP", d: ["2026-07-29", "2026-08-13", "2026-09-03", "2026-09-30", "2026-10-07"] },
  { n: "Ratatouille con quinoa", cat: "Plato Veggie", d: ["2026-07-29", "2026-08-19", "2026-09-10"] },
  { n: "Wok de cebada, cerdo, vegetales salteados y maní", cat: "Wok Gourmet", d: ["2026-07-29", "2026-08-20", "2026-09-09", "2026-10-08"] },
  { n: "Wrap de pollo, pasta de zanahorias, vegetales y quinoa con papas al chimichurri", cat: "Wrap Gourmet", d: ["2026-07-29"] },
  { n: "Milanesas de soja con jamón, queso, tomate y pesto de albahaca, acompañadas de puré de batata", cat: "Plato Light", d: ["2026-07-29"] },
  { n: "Musaka (Grecia)", cat: "Plato Etnico", d: ["2026-07-29", "2026-09-02", "2026-09-10", "2026-10-01"] },
  { n: "Font de vegetales asados, queso y croutones con reducción de soja", cat: "Vegetariano", d: ["2026-07-29", "2026-09-08"] },
  { n: "Ciabatta de jamón y queso con lechuga, tomate y huevo", cat: "Sandwich", d: ["2026-07-29", "2026-08-05", "2026-08-12", "2026-08-19", "2026-09-02", "2026-09-09", "2026-09-30", "2026-10-07"] },
  { n: "Tarta de acelga, ricotta y queso", cat: "Tarta", d: ["2026-07-29", "2026-08-10"] },
  { n: "Pizza de muzzarella con rodajas de tomate y huevo rallado", cat: "Pizza", d: ["2026-07-29"] },
  { n: "Creps de choclo, muzzarella y tomates secos, con salsa Gran Caruso", cat: "Pasta", d: ["2026-07-29"] },
  { n: "Empanadas de carne, pollo, jamón y queso", cat: "Show", d: ["2026-07-29", "2026-08-05", "2026-08-12", "2026-08-19", "2026-09-02", "2026-09-09", "2026-09-30", "2026-10-07"] },
  { n: "Berenjenas apanadas en cereal con emulsión de zanahorias y papas al verdeo", cat: "Plato Vegano Gourmet", d: ["2026-07-30"] },
  { n: "Omelette de morrón, cebolla, tomate y queso", cat: "Tortilla y Omelette", d: ["2026-07-30", "2026-08-11"] },
  { n: "Hamburguesa con rúcula, parmesano y cebollas caramelizadas, acompañada de papas provenzal", cat: "Hamburguesa Especial", d: ["2026-07-30"] },
  { n: "Tallarines con salsa bolognesa", cat: "Plato Principal 2", d: ["2026-07-30"] },
  { n: "Chambota salad, vegetales asados, cebada, mix de verdes, pollo y queso", cat: "Ensalada Gourmet", d: ["2026-07-30", "2026-09-10", "2026-10-08"] },
  { n: "Milanesa de cerdo con cheddar y verdeo, acompañada de puré mixto", cat: "Opcion Milanesa", d: ["2026-07-30"] },
  { n: "Mc Alvarez de carne con queso cheddar, panceta, cebolla caramelizada, tomate y barbacoa especiada, acompañada de papas rústicas", cat: "VAMOS CAMPEONES", d: ["2026-07-30"] },
  { n: "Ravioles de ricotta y nuez con salsa blanca y fileto", cat: "Plato Principal", d: ["2026-07-30", "2026-08-12", "2026-09-10"] },
  { n: "Wok de carne, vegetales salteados y cebada con salsa de soja ahumada", cat: "Hipernutritivo", d: ["2026-07-30"] },
  { n: "Pollo acompañado de arroz salteado con tomate seco, albahaca y nuez", cat: "Healthy Food", d: ["2026-07-30"] },
  { n: "Hojas verdes, tomates secos, hebras de queso, calabaza rústica y quinoa SAP", cat: "Ensalada SAP", d: ["2026-07-30"] },
  { n: "Humita cake con pesto de albahaca y nueces, acompañado de papas al verdeo", cat: "Plato Veggie", d: ["2026-07-30"] },
  { n: "Katsu wok con cerdo rebozado, tallarines y vegetales salteados en salsa de soja", cat: "Wok Gourmet", d: ["2026-07-30", "2026-09-02"] },
  { n: "Wrap americano con papas al pimentón", cat: "Wrap Gourmet", d: ["2026-07-30"] },
  { n: "Terrina de merluza y espinaca con salsa crema de puerros, acompañada de arroz blanco con choclo tostado", cat: "Plato Light", d: ["2026-07-30"] },
  { n: "Kibbe con hummus acompañado de batatas asadas con pimentón ahumado (Arabia)", cat: "Plato Etnico", d: ["2026-07-30"] },
  { n: "Creps de calabaza, ricotta y muzzarella con salsa crema de champignones", cat: "Vegetariano", d: ["2026-07-30"] },
  { n: "Pebetes de jamón y queso con lechuga, tomate y huevo", cat: "Sandwich", d: ["2026-07-30", "2026-08-06", "2026-08-13", "2026-08-20", "2026-09-03", "2026-09-10", "2026-10-01", "2026-10-08"] },
  { n: "Tarta Capresse", cat: "Tarta", d: ["2026-07-30", "2026-08-04", "2026-08-12", "2026-08-18", "2026-09-03", "2026-09-08", "2026-09-14"] },
  { n: "Pizza de tomates a la provenzal", cat: "Pizza", d: ["2026-07-30"] },
  { n: "Moños con salsa crema de atún", cat: "Pasta", d: ["2026-07-30"] },
  { n: "Medallón de quinoa y trigo burgol con pesto de tomates secos y puré de zapallo vegano", cat: "Plato Vegano Gourmet", d: ["2026-08-03"] },
  { n: "Tortilla de papas con queso y aceitunas negras", cat: "Tortilla y Omelette", d: ["2026-08-03", "2026-08-17", "2026-09-14", "2026-10-12"] },
  { n: "Pulled BBQ meat burger con queso, tomate y cebollas caramelizadas, acompañada de batatas y cebollas asadas", cat: "Hamburguesa Especial", d: ["2026-08-03"] },
  { n: "Fitbowl de quinoa y garbanzos con cebolla, lechuga, repollo morado, pollo, zanahoria y remolacha asada", cat: "Ensalada Gourmet", d: ["2026-08-03", "2026-09-08", "2026-10-05"] },
  { n: "Milanesa de merluza con panaché de chaucha y papa", cat: "Opcion Milanesa", d: ["2026-08-03"] },
  { n: "Mc soja Food con lechuga, tomate, cebolla y queso cheddar, acompañada de zanahorias asadas al pimentón", cat: "VAMOS CAMPEONES", d: ["2026-08-03", "2026-08-17", "2026-09-14", "2026-10-05"] },
  { n: "Milanesa de carne con queso, tomate y albahaca, acompañada de puré mixto", cat: "Plato Principal", d: ["2026-08-03"] },
  { n: "Ternerita a la española", cat: "Hipernutritivo", d: ["2026-08-03"] },
  { n: "Carré de cerdo ahumado con panaché de choclo y zanahorias", cat: "Healthy Food", d: ["2026-08-03"] },
  { n: "Ensalada rainbow, con mix de verdes, trigo burgol, tomates cherry, zanahoria, choclo y cebolla SAP", cat: "Ensalada SAP", d: ["2026-08-03", "2026-08-17", "2026-09-08", "2026-10-01"] },
  { n: "Medallón de quinoa y trigo burgol con pesto de tomates secos y puré de zapallo vegano", cat: "Plato Veggie", d: ["2026-08-03"] },
  { n: "Wok de tallarines, vegetales salteados y carne con salsa teriyaki", cat: "Wok Gourmet", d: ["2026-08-03", "2026-09-14", "2026-10-05"] },
  { n: "Wrap veggie con quinoa y chauchas, acompañado de papas al tomillo", cat: "Wrap Gourmet", d: ["2026-08-03"] },
  { n: "Roll de vegetales asados, quinoa y queso en reducción de tomate y albahaca", cat: "Plato Light", d: ["2026-08-03"] },
  { n: "Arroz Vietnamita (Vietnam)", cat: "Plato Etnico", d: ["2026-08-03", "2026-08-12", "2026-10-08"] },
  { n: "Milhojas de zucchinis con salsa cuatro quesos y semillas, acompañado de risotto crema de verdeo", cat: "Vegetariano", d: ["2026-08-03"] },
  { n: "Pebetes combinados", cat: "Sandwich", d: ["2026-08-03", "2026-08-10", "2026-08-17", "2026-08-24", "2026-09-07", "2026-09-14", "2026-10-05", "2026-10-12"] },
  { n: "Tarta asturiana", cat: "Tarta", d: ["2026-08-03", "2026-09-02", "2026-10-06"] },
  { n: "Pizza de muzzarella", cat: "Pizza", d: ["2026-08-03"] },
  { n: "Tallarines verdes a la bolognesa", cat: "Pasta", d: ["2026-08-03"] },
  { n: "Medallón vegano con emulsión de remolachas y zanahorias asadas", cat: "Plato Vegano Gourmet", d: ["2026-08-04"] },
  { n: "Omelette de queso", cat: "Tortilla y Omelette", d: ["2026-08-04", "2026-08-20", "2026-10-01", "2026-10-06"] },
  { n: "Pulled pork burger con papas al chimichurri", cat: "Hamburguesa Especial", d: ["2026-08-04"] },
  { n: "Rainbow salad con cebada, chauchas, choclo, hojas verdes, repollo, zanahoria, huevo y semillas de sésamo", cat: "Ensalada Gourmet", d: ["2026-08-04", "2026-08-18", "2026-10-06"] },
  { n: "Milanesa de carne a la napolitana, acompañada de coditos con salsa de queso y verdeo", cat: "Opcion Milanesa", d: ["2026-08-04"] },
  { n: "Bondiola a la mostaza con puré de batata y zanahoria", cat: "Plato Principal", d: ["2026-08-04"] },
  { n: "Pastel de puré mixto y merluza", cat: "Hipernutritivo", d: ["2026-08-04"] },
  { n: "Carne asada en cocción lenta con puré fiorentino", cat: "Healthy Food", d: ["2026-08-04", "2026-08-19"] },
  { n: "Hojas verdes, rúcula, fideos fussiles, pasas rubias, jamón, queso, porotos negros y tomates cherry confitados SAP", cat: "Ensalada SAP", d: ["2026-08-04"] },
  { n: "Medallón vegano con emulsión de remolachas y zanahorias asadas", cat: "Plato Veggie", d: ["2026-08-04"] },
  { n: "Wok de arroz integral, con pollo, vegetales salteados y salsa teriyaki", cat: "Wok Gourmet", d: ["2026-08-04", "2026-08-18", "2026-09-29"] },
  { n: "Wrap de carne braseada con arroz, vegetales asados y queso, acompañado de papas al verdeo", cat: "Wrap Gourmet", d: ["2026-08-04"] },
  { n: "Milanesa de queso con pesto de tomates secos y chambota de vegetales asados", cat: "Plato Light", d: ["2026-08-04"] },
  { n: "Mac and cheese (USA)", cat: "Plato Etnico", d: ["2026-08-04", "2026-08-24", "2026-09-08", "2026-10-06"] },
  { n: "Pucherito vegetal", cat: "Vegetariano", d: ["2026-08-04"] },
  { n: "Pizza de roquefort", cat: "Pizza", d: ["2026-08-04", "2026-08-11", "2026-09-01"] },
  { n: "Canelones de carne y verdura con salsa blanca y fileto", cat: "Pasta", d: ["2026-08-04", "2026-08-18", "2026-10-08"] },
  { n: "Empanadas de carne, pollo, jamón y queso, verdura", cat: "Show", d: ["2026-08-04", "2026-08-06", "2026-08-18", "2026-08-20", "2026-09-01", "2026-09-03", "2026-09-29"] },
  { n: "Berenjenas apanadas con cereal con pesto de tomates secos y zanahorias asadas con sésamo", cat: "Plato Vegano Gourmet", d: ["2026-08-05"] },
  { n: "Tortilla de papas con pimientos asados", cat: "Tortilla y Omelette", d: ["2026-08-05", "2026-09-03", "2026-10-07"] },
  { n: "Bacon Jam Burger con papas asadas a la provenzal", cat: "Hamburguesa Especial", d: ["2026-08-05", "2026-09-02"] },
  { n: "Tuna salad con arroz, lentejas, mix de verdes, papines, tomates cherry, huevo, y zanahoria", cat: "Ensalada Gourmet", d: ["2026-08-05", "2026-09-29", "2026-10-07"] },
  { n: "Milanesa de cerdo con queso cheddar y jamón tostado, acompañada de puré de batatas al verdeo", cat: "Opcion Milanesa", d: ["2026-08-05"] },
  { n: "Big Mc Food con queso cheddar, mayonesa, pepino y cebolla, acompañado de papas rústicas al pimentón", cat: "VAMOS CAMPEONES", d: ["2026-08-05"] },
  { n: "Budín de pollo con salsa crema de puerros, acompañado de papas provenzal", cat: "Plato Principal", d: ["2026-08-05"] },
  { n: "Cazuela de cerdo, papas y legumbres", cat: "Hipernutritivo", d: ["2026-08-05"] },
  { n: "Carré de cerdo ahumado con zanahorias asadas al tomillo", cat: "Healthy Food", d: ["2026-08-05"] },
  { n: "Hojas verdes, tomate, zanahoria, jamón, huevo y queso SAP", cat: "Ensalada SAP", d: ["2026-08-05"] },
  { n: "Berenjenas a la parmesana con pesto y nueces acompañado de zanahorias con sésamo", cat: "Plato Veggie", d: ["2026-08-05"] },
  { n: "Wrap de bondiola, vegetales y arroz integral con papas al pimentón", cat: "Wrap Gourmet", d: ["2026-08-05"] },
  { n: "Wok de arroz, carne braseada, vegetales salteados y salsa de soja", cat: "Plato Light", d: ["2026-08-05"] },
  { n: "Causa limeña (Perú)", cat: "Plato Etnico", d: ["2026-08-05", "2026-10-07"] },
  { n: "Empanadas veggie (lentejas, choclo criolla) con dip de hummus de garbanzos", cat: "Vegetariano", d: ["2026-08-05", "2026-09-29"] },
  { n: "Tarta de humita saludable", cat: "Tarta", d: ["2026-08-05"] },
  { n: "Pizza capresse con pesto de albahaca", cat: "Pizza", d: ["2026-08-05", "2026-08-18"] },
  { n: "Mostacholes a la bóngoli con mejillones", cat: "Pasta", d: ["2026-08-05"] },
  { n: "Curry de porotos, zanahorias, brócolis y chauchas con arroz", cat: "Plato Vegano Gourmet", d: ["2026-08-06"] },
  { n: "Omelette primavera", cat: "Tortilla y Omelette", d: ["2026-08-06", "2026-09-29"] },
  { n: "Hamburguesa francesa con queso azul, champignones, cebollas caramelizadas y tomate asado, acompañada de papas al tomillo", cat: "Hamburguesa Especial", d: ["2026-08-06"] },
  { n: "Lasagna con salsa fileto y crema", cat: "Plato Principal 2", d: ["2026-08-06", "2026-08-20", "2026-09-02", "2026-10-01"] },
  { n: "Ensalada betabel con pollo, tomates cherry, remolachas, rúcula, garbanzos y huevo", cat: "Ensalada Gourmet", d: ["2026-08-06", "2026-09-02"] },
  { n: "Milanesa de queso con tomates cherry confitados y puré de calabaza", cat: "Opcion Milanesa", d: ["2026-08-06"] },
  { n: "Mc Fernandez de pollo con queso cheddar, tomate, repollo y salsa ranch, acompañada de papas rústicas", cat: "VAMOS CAMPEONES", d: ["2026-08-06", "2026-08-13", "2026-09-08"] },
  { n: "Tagliatelli con salsa bolognesa", cat: "Plato Principal", d: ["2026-08-06", "2026-09-02"] },
  { n: "Carbonada", cat: "Hipernutritivo", d: ["2026-08-06", "2026-08-13"] },
  { n: "Pollo con puré de batata y miel", cat: "Healthy Food", d: ["2026-08-06"] },
  { n: "Ensalada gourmet con jamón y queso SAP", cat: "Ensalada SAP", d: ["2026-08-06", "2026-10-08"] },
  { n: "Curry de porotos, zanahorias, brócolis y chauchas con arroz", cat: "Plato Veggie", d: ["2026-08-06"] },
  { n: "Wok de arroz integral, vegetales salteados y almendras", cat: "Wok Gourmet", d: ["2026-08-06", "2026-08-11", "2026-09-10"] },
  { n: "Wrap de pollo y albahaca, acompañado de papas con chimichurri", cat: "Wrap Gourmet", d: ["2026-08-06", "2026-08-13"] },
  { n: "Terrina de merluza con salsa crema de champignon y boniato al horno", cat: "Plato Light", d: ["2026-08-06"] },
  { n: "Bondiola rebozada con hummus de porotos negros, crocante de maní y ensalada de chauchas y papas estilo coreano", cat: "Plato Etnico", d: ["2026-08-06"] },
  { n: "Berenjenas a la parmesana con zanahorias asadas", cat: "Vegetariano", d: ["2026-08-06"] },
  { n: "Tarta de zanahoria, verdeo y muzzarella", cat: "Tarta", d: ["2026-08-06"] },
  { n: "Pizza de muzzarella con jamón y tomates a la provenzal", cat: "Pizza", d: ["2026-08-06"] },
  { n: "Creps de acelga, ricotta y queso con salsa basílico", cat: "Pasta", d: ["2026-08-06"] },
  { n: "Albóndigas de lentejas con salsa de tomates y puré de zapallo", cat: "Plato Vegano Gourmet", d: ["2026-08-10"] },
  { n: "Tortilla de papas con jamón y queso", cat: "Tortilla y Omelette", d: ["2026-08-10"] },
  { n: "Pulled BBQ meat burger con batatas rústicas", cat: "Hamburguesa Especial", d: ["2026-08-10", "2026-09-07"] },
  { n: "Fitbowl de porotos y lentejas con cebolla, queso, tomates cherry, chauchas y choclo", cat: "Ensalada Gourmet", d: ["2026-08-10", "2026-09-07"] },
  { n: "Milanesa de berenjena a la napolitana con puré de papas al verdeo", cat: "Opcion Milanesa", d: ["2026-08-10"] },
  { n: "Mc soja Food con lechuga, tomate, cebolla y queso cheddar, acompañada de boniato asado", cat: "VAMOS CAMPEONES", d: ["2026-08-10", "2026-08-24", "2026-09-07"] },
  { n: "Milanesa de cerdo con queso, tomate y albahaca, acompañada de puré de papas", cat: "Plato Principal", d: ["2026-08-10"] },
  { n: "Feijoada", cat: "Hipernutritivo", d: ["2026-08-10", "2026-09-09", "2026-10-07"] },
  { n: "Carne asada en cocción lenta con panaché de acelga papa y zanahoria", cat: "Healthy Food", d: ["2026-08-10"] },
  { n: "Hojas verdes, tomates cherry, espinacas, papas rústicas, queso, pasas de uva y pollo al pimentón SAP", cat: "Ensalada SAP", d: ["2026-08-10"] },
  { n: "Albóndigas de lentejas con salsa de tomates, acompañadas de puré de papas", cat: "Plato Veggie", d: ["2026-08-10", "2026-08-20", "2026-09-07", "2026-10-07"] },
  { n: "Wok de pollo, tallarines y vegetales salteados con salsa teriyaki", cat: "Wok Gourmet", d: ["2026-08-10", "2026-09-07"] },
  { n: "Quesadilla de humita y panceta con zanahorias asadas en reducción de aceto", cat: "Wrap Gourmet", d: ["2026-08-10"] },
  { n: "Calzoneta de acelga, ricotta y queso con calabazas asadas al pimentón dulce", cat: "Plato Light", d: ["2026-08-10"] },
  { n: "Cazuela francesa de pollo con papas al pimentón", cat: "Plato Etnico", d: ["2026-08-10"] },
  { n: "Wok de arroz y vegetales salteados con salsa de soja y semillas", cat: "Vegetariano", d: ["2026-08-10"] },
  { n: "Pizza de muzzarella, rúcula y queso sardo", cat: "Pizza", d: ["2026-08-10", "2026-10-07"] },
  { n: "Tallarines con salsa de atún a la crema", cat: "Pasta", d: ["2026-08-10"] },
  { n: "Croquetas de arroz y espinaca veganas con pesto de tomates secos, acompañadas de papas al vapor con emulsión provenzal", cat: "Plato Vegano Gourmet", d: ["2026-08-11"] },
  { n: "Clasic pulled chicken burger con lechuga, tomate y queso, acompañada de zanahorias asadas en reducción de aceto", cat: "Hamburguesa Especial", d: ["2026-08-11"] },
  { n: "Ensalada oriental, con kani kama, huevo curado, pepino, arroz, zanahoria y semillas de sésamo", cat: "Ensalada Gourmet", d: ["2026-08-11"] },
  { n: "Cuarto de libra Food, hamburguesa doble con queso cheddar, pepino y cebolla, acompañada de papas rústicas al pimentón", cat: "VAMOS CAMPEONES", d: ["2026-08-11", "2026-09-03", "2026-09-10", "2026-09-29"] },
  { n: "Pollo asado a la provenzal, acompañado de arroz amarillo con pimientos", cat: "Plato Principal", d: ["2026-08-11"] },
  { n: "Empanada gallega con papas asadas pimentón", cat: "Hipernutritivo", d: ["2026-08-11"] },
  { n: "Carré de cerdo ahumado con panaché de chaucha, papa y zanahoria", cat: "Healthy Food", d: ["2026-08-11"] },
  { n: "Hojas verdes, tomates secos, queso, choclo, aceitunas negras, croutones y pesto de albahaca SAP", cat: "Ensalada SAP", d: ["2026-08-11", "2026-10-12"] },
  { n: "Croquetas de arroz y espinaca con pesto de tomates secos, acompañadas de papas al vapor con emulsión provenzal", cat: "Plato Veggie", d: ["2026-08-11"] },
  { n: "Wrap de bondiola y chutney con batatas glaseadas", cat: "Wrap Gourmet", d: ["2026-08-11"] },
  { n: "Zapallitos rellenos de carne, con salsa blanca, tomate concassé y pesto de albahaca, acompañados de zanahorias asadas al tomillo", cat: "Plato Light", d: ["2026-08-11"] },
  { n: "Feijoada (Brasil)", cat: "Plato Etnico", d: ["2026-08-11"] },
  { n: "Roll verde de vegetales y queso con salsa de tomate y albahaca", cat: "Vegetariano", d: ["2026-08-11"] },
  { n: "Tarta de jamón, queso y verdeo", cat: "Tarta", d: ["2026-08-11", "2026-10-12"] },
  { n: "Moños con salsa putanesca", cat: "Pasta", d: ["2026-08-11"] },
  { n: "Medallón de lentejas y vegetales con emulsión de zanahorias y calabazas asadas en mojo de hierbas", cat: "Plato Vegano Gourmet", d: ["2026-08-12"] },
  { n: "Tortilla de papas, puerro y queso", cat: "Tortilla y Omelette", d: ["2026-08-12"] },
  { n: "Hamburguesa lyonesa con queso cheddar, lomito, lechuga y cebollas caramelizadas, acompañada de zanahorias con sésamo", cat: "Hamburguesa Especial", d: ["2026-08-12"] },
  { n: "Fussiles con salsa bolognesa", cat: "Plato Principal 2", d: ["2026-08-12"] },
  { n: "Green salad con brócoli, papas, queso, zanahoria, hojas verdes, tomates cherry, pollo y semillas de lino", cat: "Ensalada Gourmet", d: ["2026-08-12", "2026-08-24", "2026-09-03", "2026-09-30"] },
  { n: "Milanesa de calabaza a la napolitana con puré de papas fiorentino", cat: "Opcion Milanesa", d: ["2026-08-12"] },
  { n: "Strogonoff de cerdo", cat: "Hipernutritivo", d: ["2026-08-12"] },
  { n: "Pollo con boniatos asados", cat: "Healthy Food", d: ["2026-08-12"] },
  { n: "Hojas verdes, lentejas, tomate, jamón y queso SAP", cat: "Ensalada SAP", d: ["2026-08-12"] },
  { n: "Medallón de lentejas y vegetales con emulsión de zanahorias y calabazas asadas en mojo de hierbas", cat: "Plato Veggie", d: ["2026-08-12"] },
  { n: "Wok de carne, cebada y vegetales salteados", cat: "Wok Gourmet", d: ["2026-08-12", "2026-09-30"] },
  { n: "Wrap americano con papas al horno y provenzal", cat: "Wrap Gourmet", d: ["2026-08-12"] },
  { n: "Milanesa de merluza crispy con batatas al horno", cat: "Plato Light", d: ["2026-08-12"] },
  { n: "Polenta con brócoli, tomates secos y hebras de queso", cat: "Vegetariano", d: ["2026-08-12"] },
  { n: "Pizza de muzzarella con tomates al ajillo", cat: "Pizza", d: ["2026-08-12", "2026-09-03"] },
  { n: "Canelones de acelga y ricotta con salsa rosé", cat: "Pasta", d: ["2026-08-12"] },
  { n: "Fainá con brócolis y calabaza", cat: "Plato Vegano Gourmet", d: ["2026-08-13"] },
  { n: "Omelette de jamón y queso", cat: "Tortilla y Omelette", d: ["2026-08-13", "2026-09-01"] },
  { n: "Hamburguesa con rúcula, parmesano y cebollas caramelizadas, acompañada de papas panaderas", cat: "Hamburguesa Especial", d: ["2026-08-13"] },
  { n: "Fitbowl de arroz y porotos negros con hojas verdes, pepino, tomates cherry, zanahoria y pollo", cat: "Ensalada Gourmet", d: ["2026-08-13", "2026-08-19"] },
  { n: "Suprema de pollo a la napolitana con arroz crema de puerros y verdeo", cat: "Opcion Milanesa", d: ["2026-08-13"] },
  { n: "Pan de carne con salsa crema de hongos, acompañado de puré de papa y zanahoria", cat: "Plato Principal", d: ["2026-08-13"] },
  { n: "Carne asada en cocción lenta con puré tricolor", cat: "Healthy Food", d: ["2026-08-13"] },
  { n: "Fainá con brócolis, calabaza y huevo duro", cat: "Plato Veggie", d: ["2026-08-13"] },
  { n: "Wok de arroz, vegetales y cerdo", cat: "Wok Gourmet", d: ["2026-08-13", "2026-10-01"] },
  { n: "Wok de cerdo, vermichellis y vegetales salteados con salsa teriyaki y mix de semillas", cat: "Plato Light", d: ["2026-08-13"] },
  { n: "Fatay con papas al pimentón", cat: "Plato Etnico", d: ["2026-08-13"] },
  { n: "Souffle de calabaza y queso con pesto de tomates secos y semillas, acompañado de acelga a la crema", cat: "Vegetariano", d: ["2026-08-13"] },
  { n: "Tarta de cebolla, muzzarella y aceitunas negras", cat: "Tarta", d: ["2026-08-13"] },
  { n: "Pizza fiorentina", cat: "Pizza", d: ["2026-08-13"] },
  { n: "Mostacholes con salsa crema de verdeo, tomate y jamón", cat: "Pasta", d: ["2026-08-13"] },
  { n: "Empanadas de carne, pollo, queso y cebolla, jamón y queso", cat: "Show", d: ["2026-08-13", "2026-10-01"] },
  { n: "Pollo con jardinera de papa, zanahoria y choclo", cat: "Healthy Food", d: ["2026-08-14", "2026-09-01"] },
  { n: "Risotto de cebada y zucchinis y nuez", cat: "Plato Vegano Gourmet", d: ["2026-08-17"] },
  { n: "Milanesa de queso con reducción de tomates cherry confitados y albahaca, acompañada de papas y brócolis al gratén", cat: "Opcion Milanesa", d: ["2026-08-17"] },
  { n: "Carne en cocción lenta con salsa portuguesa y risotto de calabaza", cat: "Plato Principal", d: ["2026-08-17"] },
  { n: "Potaje de lentejas", cat: "Hipernutritivo", d: ["2026-08-17"] },
  { n: "Bife magro de cerdo con puré de zanahoria", cat: "Healthy Food", d: ["2026-08-17"] },
  { n: "Milhojas de berenjenas con queso y reducción de tomate, acompañado de puré crema de zanahoria y acelga", cat: "Plato Light", d: ["2026-08-17"] },
  { n: "Font de vegetales asados con queso y reducción de salsa de soja", cat: "Vegetariano", d: ["2026-08-17"] },
  { n: "Tarta de choclo, jamón y muzzarella", cat: "Tarta", d: ["2026-08-17"] },
  { n: "Pizza de muzzarella con tomates cherry asados y pesto de albahaca", cat: "Pizza", d: ["2026-08-17", "2026-08-24"] },
  { n: "Kepe de trigo burgol y garbanzos con emulsión de remolacha y papas provenzal", cat: "Plato Vegano Gourmet", d: ["2026-08-18"] },
  { n: "Omelette de acelga y zanahoria", cat: "Tortilla y Omelette", d: ["2026-08-18"] },
  { n: "Pulled meat burger con queso, tomate, barbacoa y cebollas caramelizadas, acompañada de papas al pimentón", cat: "Hamburguesa Especial", d: ["2026-08-18"] },
  { n: "Milanesa de carne a la fugazzeta, acompañada de zapallitos revueltos", cat: "Opcion Milanesa", d: ["2026-08-18"] },
  { n: "Bondiola de cerdo con salsa de ciruelas y papas a la crema", cat: "Plato Principal", d: ["2026-08-18"] },
  { n: "Polenta con estofado de carne", cat: "Hipernutritivo", d: ["2026-08-18", "2026-09-29"] },
  { n: "Pollo con panaché de papa, remolacha y zanahoria", cat: "Healthy Food", d: ["2026-08-18"] },
  { n: "Ensalada completa con cubos de jamón y queso SAP", cat: "Ensalada SAP", d: ["2026-08-18"] },
  { n: "Kepe de trigo burgol y garbanzos con emulsión de remolacha y papas provenzal", cat: "Plato Veggie", d: ["2026-08-18"] },
  { n: "Wrap de bondiola, vegetales y arroz integral con batatas asadas en reducción de aceto", cat: "Wrap Gourmet", d: ["2026-08-18"] },
  { n: "Milanesa de muzzarella con reducción de tomate y albahaca, acompañada de chambota italiana", cat: "Plato Light", d: ["2026-08-18"] },
  { n: "Chow fan (China)", cat: "Plato Etnico", d: ["2026-08-18", "2026-10-05"] },
  { n: "Milhojas de calabaza rústica a la napolitana con berenjenas y cebollas asadas", cat: "Vegetariano", d: ["2026-08-18"] },
  { n: "Bacon Jam Burger con papas al tomillo", cat: "Hamburguesa Especial", d: ["2026-08-19"] },
  { n: "Milanesa de cerdo con queso, tomate y pesto de albahaca, acompañada de puré de boniato", cat: "Opcion Milanesa", d: ["2026-08-19"] },
  { n: "G.O.A.T. burger con queso cheddar, jamón tostado y cebolla crispy, acompañada de papas rústicas", cat: "VAMOS CAMPEONES", d: ["2026-08-19"] },
  { n: "Pollo al horno con salsa de pimientos rojos y curry, acompañado de batatas rústicas al romero", cat: "Plato Principal", d: ["2026-08-19"] },
  { n: "Cazuela de calamares kani kama y papas", cat: "Hipernutritivo", d: ["2026-08-19"] },
  { n: "Hojas verdes, choclo, arroz, aceitunas, tomates secos y atún", cat: "Ensalada SAP", d: ["2026-08-19", "2026-09-10"] },
  { n: "Wrap de pollo y albahaca acompañado de zanahorias con sésamo", cat: "Wrap Gourmet", d: ["2026-08-19"] },
  { n: "Zapallitos rellenos caprese con salsa fileto y arroz salteado con morrón", cat: "Plato Light", d: ["2026-08-19"] },
  { n: "Cachapas de cerdo con queso y vegetales, acompañadas de papas al verdeo", cat: "Plato Etnico", d: ["2026-08-19"] },
  { n: "Creps de humita con salsa blanca y fileto", cat: "Vegetariano", d: ["2026-08-19"] },
  { n: "Tarta de jamón, queso y cebollas", cat: "Tarta", d: ["2026-08-19", "2026-09-09"] },
  { n: "Pizza de muzzarella con verdeo", cat: "Pizza", d: ["2026-08-19"] },
  { n: "Fussiles con salsa scarparo", cat: "Pasta", d: ["2026-08-19", "2026-09-01"] },
  { n: "Albóndigas de lentejas con salsa de tomates, acompañadas de puré de zanahoria y jengibre", cat: "Plato Vegano Gourmet", d: ["2026-08-20"] },
  { n: "Hamburguesa Pons con cebolla frita, queso y barbacoa, acompañada de papas al pimentón", cat: "Hamburguesa Especial", d: ["2026-08-20"] },
  { n: "Milanesa de zucchinis a la napolitana con ratatouille mediterráneo", cat: "Opcion Milanesa", d: ["2026-08-20"] },
  { n: "Mc chicken Food con queso cheddar, pepino, cebolla y lechuga, acompañado de papas rústicas al pimentón", cat: "VAMOS CAMPEONES", d: ["2026-08-20", "2026-09-02", "2026-10-08"] },
  { n: "Tallarines a la bolognesa", cat: "Plato Principal", d: ["2026-08-20"] },
  { n: "Ragout de pollo con arroz", cat: "Hipernutritivo", d: ["2026-08-20"] },
  { n: "Pollo, acompañado de arroz salteado con champignones", cat: "Healthy Food", d: ["2026-08-20"] },
  { n: "Hojas verdes, zanahoria, tomates cherry, cubos de jamón y queso y brotes de soja SAP", cat: "Ensalada SAP", d: ["2026-08-20"] },
  { n: "Wrap de carne braseada con vegetales y batatas al pimentón", cat: "Wrap Gourmet", d: ["2026-08-20"] },
  { n: "Terrina de merluza con salsa de queso crema, verdeo y limón. acompañada de bastones de zanahoria asados al tomillo", cat: "Plato Light", d: ["2026-08-20"] },
  { n: "Taquitos de cerdo con papas al chimichurri (México)", cat: "Plato Etnico", d: ["2026-08-20"] },
  { n: "Berenjenas rellenas de quinoa, queso y ricotta con salsa blanca, acompañada de acelga y zanahorias salteadas", cat: "Vegetariano", d: ["2026-08-20"] },
  { n: "Tarta de zapallitos y muzzarella", cat: "Tarta", d: ["2026-08-20", "2026-10-08"] },
  { n: "Fugazetta con jamón", cat: "Pizza", d: ["2026-08-20"] },
  { n: "Mostacholes con salsa de queso", cat: "Pasta", d: ["2026-08-20", "2026-09-14"] },
  { n: "Curry vegano de porotos blancos, zanahorias y brócoli con pesto de albahaca y nueces, acompañado de arroz", cat: "Plato Vegano Gourmet", d: ["2026-08-24", "2026-09-02", "2026-10-08"] },
  { n: "Tortilla de brócoli, queso y tomate", cat: "Tortilla y Omelette", d: ["2026-08-24"] },
  { n: "Pulled pork burger con pepino, repollos salteados, cebollas caramelizadas y barbacoa, acompañada de papas al pimentón", cat: "Hamburguesa Especial", d: ["2026-08-24"] },
  { n: "Milanesas de berenjena con pesto de tomates secos y hebras de queso, acompañadas de arroz amarillo a la crema de puerro y verdeo", cat: "Opcion Milanesa", d: ["2026-08-24"] },
  { n: "Milanesa de carne a la fugazzeta con puré de papas", cat: "Plato Principal", d: ["2026-08-24"] },
  { n: "Albondiguitas al fileto con arroz amarillo", cat: "Hipernutritivo", d: ["2026-08-24", "2026-09-14"] },
  { n: "Carne asada en cocción lenta con puré de papas al verdeo", cat: "Healthy Food", d: ["2026-08-24"] },
  { n: "Hojas verdes, atún, tomates cherry, choclo, huevo, zanahoria y queso", cat: "Ensalada SAP", d: ["2026-08-24"] },
  { n: "Curry vegano de porotos blancos, zanahorias y brócoli con pesto de albahaca y nueces, acompañado de arroz", cat: "Plato Veggie", d: ["2026-08-24"] },
  { n: "Wok de tallarines, cerdo y vegetales salteados con salsa teriyaki", cat: "Wok Gourmet", d: ["2026-08-24"] },
  { n: "Wrap de papas rusticas vegano, acompañado de zanahorias con sésamo", cat: "Wrap Gourmet", d: ["2026-08-24"] },
  { n: "Font de vegetales asados, cubos de queso y cerdo con reducción de soja agridulce y semillas", cat: "Plato Light", d: ["2026-08-24"] },
  { n: "Risotto de calabaza y brócoli con queso y semillas", cat: "Vegetariano", d: ["2026-08-24"] },
  { n: "Tarta de queso, cebolla y aceitunas negras", cat: "Tarta", d: ["2026-08-24", "2026-09-01"] },
  { n: "Mostacholes con estofado de pollo", cat: "Pasta", d: ["2026-08-24"] },
  { n: "Clasic pulled chicken burger con lechuga, tomate y queso, acompañada de papas panaderas", cat: "Hamburguesa Especial", d: ["2026-09-01"] },
  { n: "Zucca salad con mix de verdes, porotos negros, queso, tomates cherry, calabaza apanada en polenta y maní", cat: "Ensalada Gourmet", d: ["2026-09-01"] },
  { n: "Milanesa de calabaza a la napolitana con risotto fiorentino", cat: "Opcion Milanesa", d: ["2026-09-01"] },
  { n: "Bondiola de cerdo a la fugazzetta con papas rústicas al romero", cat: "Plato Principal", d: ["2026-09-01"] },
  { n: "Cazuela de carne, arroz y legumbres", cat: "Hipernutritivo", d: ["2026-09-01"] },
  { n: "Hojas verdes, tomate, zanahoria, remolacha, papa y legumbres", cat: "Ensalada SAP", d: ["2026-09-01", "2026-09-14"] },
  { n: "Wok de cebada, vegetales salteados y salsa teriyaki", cat: "Wok Gourmet", d: ["2026-09-01"] },
  { n: "Wrap de arroz con carne braseada, vegetales asados y queso, acompañado de papas con chimichurri", cat: "Wrap Gourmet", d: ["2026-09-01"] },
  { n: "Terrina de merluza con salsa de tomates y aceitunas, acompañada de batatas al tomillo", cat: "Plato Light", d: ["2026-09-01"] },
  { n: "Polenta cremosa con estofado (Italia)", cat: "Plato Etnico", d: ["2026-09-01"] },
  { n: "Milhojas de berenjenas con salsa fileto y crema, acompañado de puré de zanahorias", cat: "Vegetariano", d: ["2026-09-01"] },
  { n: "Suprema a la fugazzetta, acompañada de coditos con salsa de queso y verdeo", cat: "Opcion Milanesa", d: ["2026-09-02"] },
  { n: "Carbonada criolla", cat: "Hipernutritivo", d: ["2026-09-02"] },
  { n: "Carré de cerdo ahumado con berenjenas, cebollas y zapallitos asados", cat: "Healthy Food", d: ["2026-09-02"] },
  { n: "Ensalada gourmet con pollo SAP", cat: "Ensalada SAP", d: ["2026-09-02"] },
  { n: "Curry de porotos blancos, zanahorias y brócoli con pesto de albahaca y nueces, acompañado de arroz", cat: "Plato Veggie", d: ["2026-09-02", "2026-10-08"] },
  { n: "Wrap de cerdo con repollos salteados y batatas al horno en reducción de aceto", cat: "Wrap Gourmet", d: ["2026-09-02"] },
  { n: "Roll verde con vegetales asados, quinoa y queso en reducción de tomate y pesto de albahaca", cat: "Plato Light", d: ["2026-09-02"] },
  { n: "Wok de arroz integral y vegetales salteados con reducción de salsa de soja", cat: "Vegetariano", d: ["2026-09-02"] },
  { n: "Pizza de muzzarella y aceitunas verdes", cat: "Pizza", d: ["2026-09-02"] },
  { n: "Canelones de verdura, pollo y queso con salsa putanesca", cat: "Pasta", d: ["2026-09-02"] },
  { n: "Kepe de trigo burgol y garbanzos con emulsión de zanahorias, acompañado de zapallitos y cebollas asados", cat: "Plato Vegano Gourmet", d: ["2026-09-03"] },
  { n: "Hamburguesa argentina con queso, tomate, cebollas caramelizadas y chimichurri, acompañada de papas al tomillo", cat: "Hamburguesa Especial", d: ["2026-09-03"] },
  { n: "Milanesa de carne con queso, tomate y pesto de albahaca, acompañada de arroz con manteca", cat: "Opcion Milanesa", d: ["2026-09-03"] },
  { n: "Pastel de papa y carne", cat: "Plato Principal", d: ["2026-09-03"] },
  { n: "Pollo con boniatos rústicos al tomillo", cat: "Healthy Food", d: ["2026-09-03"] },
  { n: "Kepe de trigo burgol y garbanzos con emulsión de zanahorias, acompañado de zapallitos y cebollas asados", cat: "Plato Veggie", d: ["2026-09-03"] },
  { n: "Wrap de pollo y albahaca con papas al pimentón", cat: "Wrap Gourmet", d: ["2026-09-03"] },
  { n: "Pechuga grillada con jamón, queso, tomate y pesto de albahaca, acompañada de pure de boniato", cat: "Plato Light", d: ["2026-09-03"] },
  { n: "Fatay con zanahorias al horno (Arabia)", cat: "Plato Etnico", d: ["2026-09-03"] },
  { n: "Fideos mostacholes con salsa parisienne", cat: "Pasta", d: ["2026-09-03"] },
  { n: "Albóndigas de lentejas con salsa de tomates, acompañadas de puré de papas vegano", cat: "Plato Vegano Gourmet", d: ["2026-09-07"] },
  { n: "Tortilla de papas tradicional", cat: "Tortilla y Omelette", d: ["2026-09-07"] },
  { n: "Milanesa de pescado con revuelto de zapallitos", cat: "Opcion Milanesa", d: ["2026-09-07"] },
  { n: "Suprema de pollo con queso cheddar y verdeo, acompañada de puré de papas", cat: "Plato Principal", d: ["2026-09-07"] },
  { n: "Calamares a la provenzal con arroz", cat: "Hipernutritivo", d: ["2026-09-07"] },
  { n: "Bife de cerdo ahumado con jardinera", cat: "Healthy Food", d: ["2026-09-07"] },
  { n: "Hojas verdes, radicchio, choclo tostado, quinoa, queso, tomate, pechuga de pollo ahumada y mix de semillas", cat: "Ensalada SAP", d: ["2026-09-07"] },
  { n: "Quesadilla de humita y panceta, acompañada de papas al verdeo", cat: "Wrap Gourmet", d: ["2026-09-07"] },
  { n: "Creps de humita y muzzarella, con salsa fileto y crema", cat: "Plato Light", d: ["2026-09-07"] },
  { n: "Cachapas con cerdo y queso, acompañadas de papas al chimichurri (Venezuela)", cat: "Plato Etnico", d: ["2026-09-07"] },
  { n: "Pastel de papas y lentejas", cat: "Vegetariano", d: ["2026-09-07"] },
  { n: "Tarta de puerro y queso", cat: "Tarta", d: ["2026-09-07"] },
  { n: "Pizza de muzzarella y pesto de tomates secos", cat: "Pizza", d: ["2026-09-07"] },
  { n: "Tallarines con salsa crema de puerros, jamón, champignones y vino blanco", cat: "Pasta", d: ["2026-09-07"] },
  { n: "Medallón vegano con emulsión de remolachas y papas al pimentón", cat: "Plato Vegano Gourmet", d: ["2026-09-08"] },
  { n: "Omelette de Espinaca y queso", cat: "Tortilla y Omelette", d: ["2026-09-08"] },
  { n: "Pulled pork burger con pepino, repollos salteados, cebollas caramelizadas y barbacoa, acompañada de papas provenzal", cat: "Hamburguesa Especial", d: ["2026-09-08"] },
  { n: "Milanesa de carne con queso, tomate y pesto de albahaca, acompañada de coditos con salsa de queso y verdeo", cat: "Opcion Milanesa", d: ["2026-09-08"] },
  { n: "Jamón de cerdo con salsa de ciruelas, acompañado de risotto de zanahorias", cat: "Plato Principal", d: ["2026-09-08"] },
  { n: "Strogonoff", cat: "Hipernutritivo", d: ["2026-09-08"] },
  { n: "Pollo dieta con puré de batata al verdeo", cat: "Healthy Food", d: ["2026-09-08"] },
  { n: "Medallón vegano con emulsión de remolachas y papas al pimentón", cat: "Plato Veggie", d: ["2026-09-08"] },
  { n: "Wok de arroz, vegetales salteados y carne", cat: "Wok Gourmet", d: ["2026-09-08", "2026-10-07"] },
  { n: "Milanesas de soja con jamón, queso, tomate y albahaca, acompañadas de puré fiorentino", cat: "Plato Light", d: ["2026-09-08"] },
  { n: "Pizza cuatro quesos", cat: "Pizza", d: ["2026-09-08", "2026-10-06"] },
  { n: "Moños con salsa de verdeo, tomate y jamón a la crema", cat: "Pasta", d: ["2026-09-08"] },
  { n: "Kepe de trigo burgol y garbanzos con emulsión de zanahorias y batatas glaseadas", cat: "Plato Vegano Gourmet", d: ["2026-09-09"] },
  { n: "Tortilla de papa y zapallitos", cat: "Tortilla y Omelette", d: ["2026-09-09"] },
  { n: "Hamburguesa francesa con queso azul, champignones, cebollas caramelizadas y tomate asado, acompañada de papas cuña al chimichurri", cat: "Hamburguesa Especial", d: ["2026-09-09"] },
  { n: "Milanesa de cerdo a la fiorentina con puré de papas y brócoli", cat: "Opcion Milanesa", d: ["2026-09-09"] },
  { n: "Pollo al horno con chimichurri, acompañado de batatas asadas al romero", cat: "Plato Principal", d: ["2026-09-09"] },
  { n: "Carne asada en cocción lenta con risotto de champignones", cat: "Healthy Food", d: ["2026-09-09"] },
  { n: "Hojas verdes, arroz, choclo, huevo, tomate, jamón, queso y zanahoria SAP", cat: "Ensalada SAP", d: ["2026-09-09"] },
  { n: "Kepe de trigo burgol y garbanzos con emulsión de zanahorias y batatas glaseadas", cat: "Plato Veggie", d: ["2026-09-09"] },
  { n: "Wrap de pollo, vegetales y quinoa con papas al tomillo", cat: "Wrap Gourmet", d: ["2026-09-09"] },
  { n: "Wok de vermichellis, vegetales salteados y carne con salsa de teriyaki y semillas", cat: "Plato Light", d: ["2026-09-09"] },
  { n: "Berenjenas a la parmesana con arroz amarillo", cat: "Vegetariano", d: ["2026-09-09"] },
  { n: "Pizza de muzzarella con orégano", cat: "Pizza", d: ["2026-09-09"] },
  { n: "Canelones de acelga, calabaza y ricotta con salsa capresse", cat: "Pasta", d: ["2026-09-09"] },
  { n: "Tortilla de papa con salame y queso", cat: "Tortilla y Omelette", d: ["2026-09-10"] },
  { n: "Hamburguesa con rúcula, parmesano y cebollas caramelizadas, acompañada de papas al verdeo", cat: "Hamburguesa Especial", d: ["2026-09-10"] },
  { n: "Mostacholes a la bolognesa", cat: "Plato Principal 2", d: ["2026-09-10"] },
  { n: "Milanesa de queso con salsa crema de cebollas y chambota", cat: "Opcion Milanesa", d: ["2026-09-10"] },
  { n: "Pastel de pollo a la napolitana", cat: "Hipernutritivo", d: ["2026-09-10"] },
  { n: "Carré de cerdo ahumado con puré crema de zanahorias", cat: "Healthy Food", d: ["2026-09-10"] },
  { n: "Wrap americano con papas al chimichurri", cat: "Wrap Gourmet", d: ["2026-09-10", "2026-10-08"] },
  { n: "Pechuga grillé con salsa crema de choclo y zapallitos revueltos", cat: "Plato Light", d: ["2026-09-10"] },
  { n: "Creps capresse de ricotta, muzzarella, tomate seco y albahaca con salsa blanca y fileto", cat: "Vegetariano", d: ["2026-09-10"] },
  { n: "Tarta de choclo, verdeo y muzzarella", cat: "Tarta", d: ["2026-09-10"] },
  { n: "Pizza de jamón y muzzarella", cat: "Pizza", d: ["2026-09-10", "2026-09-30"] },
  { n: "Coditos con salsa crema de champignon", cat: "Pasta", d: ["2026-09-10"] },
  { n: "Croquetas de arroz y espinaca veganas con emulsión de remolachas, acompañadas de zanahorias asadas con sésamo", cat: "Plato Vegano Gourmet", d: ["2026-09-14"] },
  { n: "Hamburguesa de pollo con queso, cebolla y ketchup, acompañada de batatas al horno", cat: "Hamburguesa Especial", d: ["2026-09-14"] },
  { n: "Milanesas de berenjena a la napolitana con puré de batata y zanahoria", cat: "Opcion Milanesa", d: ["2026-09-14"] },
  { n: "Milanesa de cerdo con queso, tomate y albahaca, acompañada de puré fiorentino", cat: "Plato Principal", d: ["2026-09-14"] },
  { n: "Carré de cerdo ahumado con zanahorias asadas en pimentón dulce", cat: "Healthy Food", d: ["2026-09-14"] },
  { n: "Croquetas de arroz y espinaca con emulsión de remolachas, acompañadas de zanahorias asadas con sésamo", cat: "Plato Veggie", d: ["2026-09-14"] },
  { n: "Wrap veggie de arroz integral y vegetales asados con papas provenzal", cat: "Wrap Gourmet", d: ["2026-09-14"] },
  { n: "Terrina de merluza con salsa de queso y arroz cremoso al verdeo", cat: "Plato Light", d: ["2026-09-14"] },
  { n: "Curry de pollo (India)", cat: "Plato Etnico", d: ["2026-09-14"] },
  { n: "Roll de vegetales y queso con salsa de tomates y albahaca", cat: "Vegetariano", d: ["2026-09-14"] },
  { n: "Pizza de muzzarella con tomates cherry asados", cat: "Pizza", d: ["2026-09-14"] },
  { n: "Kepe de trigo burgol y garbanzos con emulsión de remolachas y zanahorias al pimentón", cat: "Plato Vegano Gourmet", d: ["2026-09-29"] },
  { n: "Pulled pork burger con batatas glaseadas", cat: "Hamburguesa Especial", d: ["2026-09-29"] },
  { n: "Milanesa de cerdo con queso y tomate concasé, acompañada de puré de papas al verdeo", cat: "Opcion Milanesa", d: ["2026-09-29"] },
  { n: "Pollo asado a la provenzal con boniatos al horno", cat: "Plato Principal", d: ["2026-09-29"] },
  { n: "Bife magro de cerdo con papas asadas al tomillo", cat: "Healthy Food", d: ["2026-09-29"] },
  { n: "Ensalada de hojas verdes arroz integral choclo porotos tomate seco y queso en hebras SAP", cat: "Ensalada SAP", d: ["2026-09-29"] },
  { n: "Kepe de trigo burgol y garbanzos con emulsión de remolachas y zanahorias al pimentón", cat: "Plato Veggie", d: ["2026-09-29"] },
  { n: "Wrap de carne braseada, arroz, vegetales asados y queso, acompañado de papas al tomillo", cat: "Wrap Gourmet", d: ["2026-09-29"] },
  { n: "Font de vegetales asados con carne, cubos de queso y salsa teriyaki", cat: "Plato Light", d: ["2026-09-29"] },
  { n: "Taquitos de cerdo con papas provenzal (México)", cat: "Plato Etnico", d: ["2026-09-29"] },
  { n: "Tarta de choclo, pollo y muzzarella", cat: "Tarta", d: ["2026-09-29"] },
  { n: "Pizza de muzzarella con cebollas asadas", cat: "Pizza", d: ["2026-09-29", "2026-10-08"] },
  { n: "Canelones de jamón, ricotta y nuez con salsa putanesca", cat: "Pasta", d: ["2026-09-29"] },
  { n: "Risotto de cebada, calabaza y almendras", cat: "Plato Vegano Gourmet", d: ["2026-09-30"] },
  { n: "Tortilla de acelga y queso", cat: "Tortilla y Omelette", d: ["2026-09-30"] },
  { n: "Hamburguesa clásica con lechuga, tomate y queso, acompañada de papas al tomillo", cat: "Hamburguesa Especial", d: ["2026-09-30"] },
  { n: "Milanesa de muzzarella con tomates cherry confitados y albahaca, acompañada de chambota italiana", cat: "Opcion Milanesa", d: ["2026-09-30"] },
  { n: "Pan de carne con salsa de mostaza y miel, acompañado de papas rústicas al pimentón", cat: "Plato Principal", d: ["2026-09-30"] },
  { n: "Cubos de cerdo braseado con barbacoa y verdeo, acompañados de puré de batatas rústicas", cat: "Hipernutritivo", d: ["2026-09-30"] },
  { n: "Carne asada en cocción lenta con zapallitos revueltos", cat: "Healthy Food", d: ["2026-09-30"] },
  { n: "Risotto de cebada, calabaza y almendras", cat: "Plato Veggie", d: ["2026-09-30"] },
  { n: "Wrap de bondiola y chutney con batatas asadas en reducción de aceto", cat: "Wrap Gourmet", d: ["2026-09-30"] },
  { n: "Canelones de verdura y ricotta con salsa de tomates y albahaca", cat: "Plato Light", d: ["2026-09-30"] },
  { n: "Kibbe con hummus acompañado de papas al pimentón (Arabia)", cat: "Plato Etnico", d: ["2026-09-30"] },
  { n: "Milanesas de soja con salsa crema de choclo y verdeo, acompañadas de papas y brócolis al gratén", cat: "Vegetariano", d: ["2026-09-30"] },
  { n: "Tarta de muzzarella, aceitunas negras y tomates secos", cat: "Tarta", d: ["2026-09-30"] },
  { n: "Penne rigatti con salsa scarparo", cat: "Pasta", d: ["2026-09-30"] },
  { n: "Medallón vegano con emulsión de remolachas, acompañado de zapallitos y cebollas asadas", cat: "Plato Vegano Gourmet", d: ["2026-10-01"] },
  { n: "Hamburguesa americana con panceta, barbacoa, tomate y cebolla caramelizada, acompañada de papas cubo a la provenzal", cat: "Hamburguesa Especial", d: ["2026-10-01"] },
  { n: "Suprema de pollo con queso, tomate y pesto de albahaca, acompañada de acelga salteada con zanahoria", cat: "Opcion Milanesa", d: ["2026-10-01"] },
  { n: "Fussiles con salsa parisienne", cat: "Plato Principal", d: ["2026-10-01"] },
  { n: "Cazuela de calamares con arroz", cat: "Hipernutritivo", d: ["2026-10-01"] },
  { n: "Carré de cerdo ahumado con puré de papas al verdeo", cat: "Healthy Food", d: ["2026-10-01"] },
  { n: "Medallón vegano con emulsión de remolachas, acompañado de zapallitos y cebollas asadas", cat: "Plato Veggie", d: ["2026-10-01"] },
  { n: "Wrap de pollo, vegetales y quinoa, acompañado de papas al pimentón", cat: "Wrap Gourmet", d: ["2026-10-01"] },
  { n: "Wok de cerdo con arroz, vegetales salteados y salsa teriyaki", cat: "Plato Light", d: ["2026-10-01"] },
  { n: "Guenel con salsa blanca, fileto y hebras de queso", cat: "Vegetariano", d: ["2026-10-01"] },
  { n: "Tarta de vegetales asados y muzzarella", cat: "Tarta", d: ["2026-10-01"] },
  { n: "Pizza de muzzarella con tomates concasé y orégano", cat: "Pizza", d: ["2026-10-01"] },
  { n: "Fussiles al pesto", cat: "Pasta", d: ["2026-10-01"] },
  { n: "Croquetas de arroz y espinaca veganas con pesto de tomates secos y zanahorias asadas", cat: "Plato Vegano Gourmet", d: ["2026-10-05"] },
  { n: "Hamburguesa de pollo desmechado con queso, lechuga, tomate, cebollas caramelizadas y emulsión provenzal, acompañada de batatas al horno", cat: "Hamburguesa Especial", d: ["2026-10-05"] },
  { n: "Milanesa de zucchinis con reducción de tomate y albahaca, acompañada de puré crema de zanahorias y brócolis", cat: "Opcion Milanesa", d: ["2026-10-05"] },
  { n: "Milanesa de cerdo con queso, tomate y pesto de albahaca, acompañada de puré mixto", cat: "Plato Principal", d: ["2026-10-05"] },
  { n: "Plato de fiambres con ensalada rusa", cat: "Hipernutritivo", d: ["2026-10-05"] },
  { n: "Carne asada en cocción lenta con risotto amarillo de verdeo y puerro", cat: "Healthy Food", d: ["2026-10-05"] },
  { n: "Espinacas, radicchio, quinoa, pollo ahumado, tomate, cubos de queso y choclo tostado SAP", cat: "Ensalada SAP", d: ["2026-10-05"] },
  { n: "Croquetas de arroz y espinaca con pesto de tomates secos y zanahorias asadas", cat: "Plato Veggie", d: ["2026-10-05"] },
  { n: "Wrap de lentejas con zanahorias asadas", cat: "Wrap Gourmet", d: ["2026-10-05"] },
  { n: "Calzonetta de espinaca, ricotta y tomates secos con bastones de zanahoria asada al tomillo", cat: "Plato Light", d: ["2026-10-05"] },
  { n: "Milhojas de berenjenas con salsa blanca y fileto, acompañado de arroz salteado con feijón y perejil", cat: "Vegetariano", d: ["2026-10-05"] },
  { n: "Tarta de zapallitos", cat: "Tarta", d: ["2026-10-05"] },
  { n: "Pizza de muzzarella y huevo rallado", cat: "Pizza", d: ["2026-10-05"] },
  { n: "Mostacholes con salsa parisienne", cat: "Pasta", d: ["2026-10-05"] },
  { n: "Guiso de lentejas vegano", cat: "Plato Vegano Gourmet", d: ["2026-10-06"] },
  { n: "Clasic pulled chicken burger con lechuga, tomate y queso, acompañada de zanahorias asadas", cat: "Hamburguesa Especial", d: ["2026-10-06"] },
  { n: "Milanesa de cerdo a la fiorentina con puré de papas", cat: "Opcion Milanesa", d: ["2026-10-06"] },
  { n: "Dibu burger con queso, huevo revuelto y palta, acompañada de papas rústicas al pimentón", cat: "VAMOS CAMPEONES", d: ["2026-10-06"] },
  { n: "Pollo al horno con reducción de soja ahumada, y arroz cremoso al verdeo", cat: "Plato Principal", d: ["2026-10-06"] },
  { n: "Poke Bowl oriental, con arroz, vegetales al escabeche y mayonesa de pescado", cat: "Hipernutritivo", d: ["2026-10-06"] },
  { n: "Carré de cerdo ahumado con batatas al horno", cat: "Healthy Food", d: ["2026-10-06"] },
  { n: "Hojas verdes, arroz, jamón, queso, choclo, tomates secos y huevo SAP", cat: "Ensalada SAP", d: ["2026-10-06"] },
  { n: "Risotto de cebada, calabaza y almendras con pesto de albahaca", cat: "Plato Veggie", d: ["2026-10-06"] },
  { n: "Wok de cebada, pollo y vegetales salteados con salsa teriyaki y sésamo", cat: "Wok Gourmet", d: ["2026-10-06"] },
  { n: "Wrap de cerdo con repollos salteados y barbacoa, acompañado de papas y batatas asadas", cat: "Wrap Gourmet", d: ["2026-10-06"] },
  { n: "Rollitos de merluza con salsa crema de champignones y semillas, acompañados de papas a la provenzal", cat: "Plato Light", d: ["2026-10-06"] },
  { n: "Terrina de zapallitos y tomates secos con salsa blanca y remolachas asadas", cat: "Vegetariano", d: ["2026-10-06"] },
  { n: "Creps de brócoli, ricotta y muzzarella con salsa rosé", cat: "Pasta", d: ["2026-10-06"] },
  { n: "Hamburguesa de pollo clásica con lechuga, tomate y queso, acompañada de papas asadas a la provenzal", cat: "Hamburguesa Especial", d: ["2026-10-07"] },
  { n: "Milanesa de carne con queso y tomate, acompañada de coditos con salsa de queso y verdeo", cat: "Opcion Milanesa", d: ["2026-10-07"] },
  { n: "Parrillada de bondiola de cerdo y dos chorizos con salsa criolla y papas al horno", cat: "Plato Principal", d: ["2026-10-07"] },
  { n: "Pollo con puré fiorentino", cat: "Healthy Food", d: ["2026-10-07"] },
  { n: "Wrap de pollo y albahaca con batatas glaseadas", cat: "Wrap Gourmet", d: ["2026-10-07"] },
  { n: "Risotto de berenjenas, tomates secos y muzzarella", cat: "Plato Light", d: ["2026-10-07"] },
  { n: "Milhojas de vegetales con salsa de queso y boniatos rústicos al tomillo", cat: "Vegetariano", d: ["2026-10-07"] },
  { n: "Tarta de zanahoria, espinaca y queso", cat: "Tarta", d: ["2026-10-07"] },
  { n: "Tagliatelli con salsa Gran Caruso", cat: "Pasta", d: ["2026-10-07"] },
  { n: "Omelette de verdeo, tomate y queso", cat: "Tortilla y Omelette", d: ["2026-10-08"] },
  { n: "Hamburguesa francesa con queso azul, champignones, cebollas caramelizadas y tomate asado, acompañada de batatas al horno", cat: "Hamburguesa Especial", d: ["2026-10-08"] },
  { n: "Fideos tagliatelli con salsa bolognesa", cat: "Plato Principal 2", d: ["2026-10-08"] },
  { n: "Milanesa de berenjena a la fugazzetta con puré de batata y miel", cat: "Opcion Milanesa", d: ["2026-10-08"] },
  { n: "Ravioles de ricotta y nuez con salsa rosa", cat: "Plato Principal", d: ["2026-10-08"] },
  { n: "Arrollado primavera con papas perejiladas", cat: "Hipernutritivo", d: ["2026-10-08"] },
  { n: "Carne asada en cocción lenta con boniatos rústicos al tomillo", cat: "Healthy Food", d: ["2026-10-08"] },
  { n: "Pastel de papas y pollo", cat: "Plato Light", d: ["2026-10-08"] },
  { n: "Milanesa de queso con salsa crema de cebollas y puré de zanahorias", cat: "Vegetariano", d: ["2026-10-08"] },
  { n: "Carré de cerdo a la pizza con puré de papas al verdeo", cat: "Plato Principal", d: ["2026-10-12"] },
  { n: "Carne asada en cocción lenta con chambota", cat: "Healthy Food", d: ["2026-10-12"] },
  { n: "Pechuga grillé con salsa crema de choclo, acompañada de panaché de choclo, chaucha y remolacha", cat: "Plato Light", d: ["2026-10-12"] },
  { n: "Millhojas de calabaza con salsa de brócolis y zapallitos salteados", cat: "Vegetariano", d: ["2026-10-12"] },
  { n: "Pizza de muzzarella y pesto de albahaca", cat: "Pizza", d: ["2026-10-12"] },
];

// Convertimos cada plato al formato de la app: k = kcal de la porción entera,
// con p=100 la porción se representa como "100" en el campo de gramos (100 = plato entero, 50 = medio plato).
const ALIMENTOS_TRABAJO = PLATOS_TRABAJO.map(p => {
  const cat = CATEGORIAS_TRABAJO[p.cat] || { kcal: 600, alias: [] };
  return {
    n: p.n,
    a: [...cat.alias, p.cat.toLowerCase()],
    k: cat.kcal, p: 100, u: "1 porción",
    trabajo: true, dias: p.d,
  };
});
